//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTVEntityFramwork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Detail
    {
        public string TENSACH { get; set; }
        public string VITRI { get; set; }
        public string LINHVUC { get; set; }
        public Nullable<int> GIA { get; set; }
        public Nullable<int> TONGSOLUONG { get; set; }
    }
}
