//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTVEntityFramwork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrower_Info
    {
        public int MAUSER { get; set; }
        public string TEN { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
    }
}
