//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTVEntityFramwork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing_Details
    {
        public string TenUser { get; set; }
        public string TenSach { get; set; }
        public string NGAYMUON { get; set; }
        public string NGAYTRA { get; set; }
        public string TINHTRANG { get; set; }
    }
}
