//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTVEntityFramwork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD
    {
        public int MACARD { get; set; }
        public Nullable<int> MAUSER { get; set; }
        public string NUMBERCARD { get; set; }
        public string DATESTART { get; set; }
        public string DATEFINISH { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
