//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTVEntityFramwork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUONSACH
    {
        public int MAUSER { get; set; }
        public int MASACH { get; set; }
        public Nullable<System.DateTime> NGAYMUON { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<int> SOLUONGSACHMUON { get; set; }
        public Nullable<int> SOLUONGSACHTRA { get; set; }
        public Nullable<int> SOLUONGSACHMAT { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual USER USER { get; set; }
    }
}
