//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTVEntityFramwork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.MUONSACHes = new HashSet<MUONSACH>();
        }
    
        public int MASACH { get; set; }
        public Nullable<int> MANXB { get; set; }
        public Nullable<int> MATACGIA { get; set; }
        public string VITRI { get; set; }
        public string TENSACH { get; set; }
        public Nullable<int> DANGDUOCMUON { get; set; }
        public Nullable<int> TONGSOLUONG { get; set; }
        public Nullable<int> SOLUONGSACHBIMAT { get; set; }
        public string LINHVUC { get; set; }
        public Nullable<int> GIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUONSACH> MUONSACHes { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TACGIA TACGIA { get; set; }
    }
}
